pipeline:
  name: Enterprise FHIRV2 89728238
  identifier: enterprise_fhirv2_89728238
  projectIdentifier: CSETest1
  orgIdentifier: nglabs
  description: 'Migrated pipeline: Enterprise FHIRV2 89728238. Review connectors,
    secrets, and runtime inputs before production use.'
  tags: {}
  template:
    templateRef: account.spring_boot_helm_pipeline_filled_HEALTH_FHIRV2
    versionLabel: v1
    gitBranch: ank1064-patch-1
    templateInputs:
      variables:
      - name: imageRegistry
        type: String
        value: <+input>
      - name: helmChart
        type: String
        value: <+input>
      - name: fhirProfile
        type: String
        value: <+input>
      - name: dastTarget
        type: String
        value: <+input>
      - name: sonarProject
        type: String
        value: <+input>
      - name: integrationHealthCheckUrl
        type: String
        value: <+input>
      - name: clinicalUatHealthCheckUrl
        type: String
        value: <+input>
      - name: productionHealthCheckUrl
        type: String
        value: <+input>
      stages:
      - stage:
          identifier: DeployIntegration
          type: Deployment
          spec:
            service:
              serviceRef: <+input>
            environment:
              environmentRef: <+input>
              infrastructureDefinitions:
              - identifier: <+input>
      - stage:
          identifier: DeployClinicalUAT
          type: Deployment
          spec:
            service:
              serviceRef: <+input>
            environment:
              environmentRef: <+input>
              infrastructureDefinitions:
              - identifier: <+input>
      - stage:
          identifier: ProductionBlueGreenDeployment
          type: Deployment
          spec:
            service:
              serviceRef: <+input>
            environment:
              environmentRef: <+input>
              infrastructureDefinitions:
              - identifier: <+input>
      - stage:
          identifier: DeployAuditCanary
          type: Deployment
          spec:
            service:
              serviceRef: <+input>
            environment:
              environmentRef: <+input>
              infrastructureDefinitions:
              - identifier: <+input>
