pipeline:
  name: GHA Map gha_map_remote 233240
  identifier: gha_map_gha_map_remote_233240
  projectIdentifier: CSETest1
  orgIdentifier: nglabs
  description: ''
  tags: {}
  template:
    templateRef: ci_full_pipeline_template
    versionLabel: v1
    templateInputs:
      stages:
      - stage:
          identifier: build_and_test
          type: CI
          spec:
            infrastructure:
              spec:
                connectorRef: <+input>
                namespace: <+input>
