pipeline:
  name: Live remote 74179618
  identifier: live_remote_74179618
  projectIdentifier: CSETest1
  orgIdentifier: nglabs
  description: 'Migrated pipeline: Live remote 74179618. Review connectors, secrets,
    and runtime inputs before production use.'
  tags: {}
  stages:
  - stage:
      name: Build  Test
      identifier: Build_Test
      description: 'Bamboo env: Build & Test'
      template:
        templateRef: account.SCR
        versionLabel: '1'
        templateInputs:
          type: Custom
  - stage:
      name: Package
      identifier: Package
      description: 'Bamboo env: Package'
      template:
        templateRef: account.SCR
        versionLabel: '1'
        templateInputs:
          type: Custom
